### Interpolação quadrática

In [7]:
import matplotlib.pyplot as plt
import numpy as np

In [8]:
(x0, y0) = (0,0)
(x1, y1) = (1,1)
(x2, y2) = (4,4)

p0 = (x0, y0)
p1 = (x1, y1)
p2 = (x2, y2)

M = np.zeros([3,3])
M

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
M[0,0] = 1
M[0,1] = x0
M[0,2] = x0**2

M[1,0] = 1
M[1,1] = x1
M[1,2] = x1**2

M[2,0] = 1
M[2,1] = x2
M[2,2] = x2**2

"""
for i in range(3):
  for j in range(3):
    M[i,j]
"""

'\nfor i in range(3):\n  for j in range(3):\n    M[i,j]\n'

In [10]:
M

array([[ 1.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  4., 16.]])

In [12]:
y = np.array([y0, y1, y2])

N = np.linalg.inv(M)

print(np.matmul(M,N))

[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 1.38777878e-17]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
