Pacote Numpy

O pacote numpy é fundamental para computação científica com Python. Ele oferece funções matemáticas, geradores de números aleatórios, rotinas de álgebra linear, transformada de Fourier e muito mais. Mas o seu poder está em permitir cálculos em arrays multidimensionais.

O numpy executa facilmente cálculos numéricos que são muito utilizados em problemas de machine learning (aprendizado de máquina) e de processamento de imagem (imagens no computador são representadas como arrays multidimensionais de números). Além disso, o numpy oferece várias outras tarefas matemáticas.

Para mais informações, consulte https://numpy.org/.
Arrays¶

Um array é um conjunto ordenado de valores. Mas há diferenças importantes entre listas e arrays:

    O número de elementos de um array é fixo e não é possível adicionar ou remover elementos de um array após criá-lo;
    Os elementos de um array devem ser todos de um mesmo tipo, como float ou inteiros.

As principais vantagens de usar arrays em vez de listas são:

    Arrays podem ter qualquer número de dimensões. Arrays unidimensionais e bidimensionais são, respectivamente, como vetores e matrizes em álgebra linear. Listas são sempre unidimensionais.
    Como se comportam como vetores ou matrizes, podemos fazer qualquer aritmética com eles, ao contrário de listas.
    Arrays funcionam mais rápido que listas em Python.

Cada dimensão de um array é chamada axis. O número de axes é chamada de rank do array. A indexação dos arrays também começa em 0, com um número para cada axis do array.


In [1]:
import numpy as np

In [2]:
np.array([6, 28, 496, 8128])

array([   6,   28,  496, 8128])

In [3]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [4]:
np.zeros(4)

array([0., 0., 0., 0.])

In [5]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
x=np.empty(4)
x

array([0., 0., 0., 0.])

In [7]:
np.empty(4)

array([0., 0., 0., 0.])

In [8]:
np.linspace(1, 2, 5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
np.logspace(1, -1, 3)

array([10. ,  1. ,  0.1])

In [10]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [11]:
y = np.linspace(-2, 2, 100)
x = np.linspace(-2, 2, 100)
z = np.meshgrid(x, y)
np.size(z)

20000

In [12]:
a.shape = (2, 2)
a

array([[0, 1],
       [2, 3]])

In [13]:
a = np.array([6, 28, 496, 8128])
a.dtype

dtype('int64')

In [14]:
b = np.array([6, 28.0, 496, 8128])
b.dtype

dtype('float64')

In [15]:
a = np.array([6, 28.0, 496, 8128],
             dtype=np.int8) #números inteiros de 8 bits
a

array([  6,  28, -16, -64], dtype=int8)

In [16]:
b = np.array([6, 28.0, 496, 8128],
             dtype='f') 
b

array([6.000e+00, 2.800e+01, 4.960e+02, 8.128e+03], dtype=float32)

In [17]:
np.array(['I will have length six', 'and so will I!'], dtype='S6')

array([b'I will', b'and so'], dtype='|S6')

In [18]:
a = np.arange(8)

In [19]:
a[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
a[2:6]

array([2, 3, 4, 5])

In [21]:
a[1::3]

array([1, 4, 7])

In [22]:
a = np.arange(16)
a.shape = (4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
a[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [24]:
a[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [25]:
a[2::-1, :3]     

array([[ 8,  9, 10],
       [ 4,  5,  6],
       [ 0,  1,  2]])

In [26]:
a = np.arange(6)
b = a[1::2]
b[1] = 42
a

array([ 0,  1,  2, 42,  4,  5])

In [27]:
b.base is a

True

In [28]:
a = np.arange(16)
b = np.array(a[1::11])

In [29]:
a = np.arange(6, dtype=np.int64)
a

array([0, 1, 2, 3, 4, 5])

In [30]:
a.view('i4')

array([0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 5, 0], dtype=int32)

In [31]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [32]:
a - 1

array([-1,  0,  1,  2,  3,  4])

In [33]:
a + a

array([ 0,  2,  4,  6,  8, 10])

In [34]:
2*a**2 + 3*a + 1

array([ 1,  6, 15, 28, 45, 66])

In [35]:
a = np.arange(4)
a.shape = (2, 2)
a

array([[0, 1],
       [2, 3]])

In [36]:
b = np.array([[42], [43]])
b

array([[42],
       [43]])

In [37]:
a * b

array([[  0,  42],
       [ 86, 129]])

In [38]:
np.dot(a, b)

array([[ 43],
       [213]])

In [39]:
np.array([[ 43],
      [213]])

array([[ 43],
       [213]])

In [40]:
a = np.arange(12)
a.shape = (4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
b = np.array([16, 17, 18])
b

array([16, 17, 18])

In [42]:
a + b

array([[16, 18, 20],
       [19, 21, 23],
       [22, 24, 26],
       [25, 27, 29]])

In [43]:
a.shape = (3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a + b

ValueError: ignored

In [46]:
b.shape = (3, 1)
b

array([[16],
       [17],
       [18]])

In [47]:
a + b

array([[16, 17, 18, 19],
       [21, 22, 23, 24],
       [26, 27, 28, 29]])

In [48]:
a = np.arange(6)
a.shape = (2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
b = np.array([2, 3])
b

array([2, 3])

In [50]:
a - b

ValueError: ignored

In [51]:
b[:, np.newaxis] - a

array([[ 2,  1,  0],
       [ 0, -1, -2]])

In [52]:
b[(slice(None),) + 31* (np.newaxis,)] - a

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ 2,
                                       1,
                                       0],
                                     [-1,
                                      -2,
                                      -3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]],






























       [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ 3,
                                       2,
                                       1],
                                     [ 0,
                                      -1,
                                      -2]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [53]:
b[(slice(None),) + 30 * (np.newaxis,)] - a

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ 2,  1,
                                      0],
                                    [-1, -2,
                                     -3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]],





























       [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ 3,  2,
                                      1],
                                    [ 0, -1,
                                     -2]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [54]:
a = 2*np.arange(8)**2 + 1
a

array([ 1,  3,  9, 19, 33, 51, 73, 99])

In [55]:
# pull out the fourth, last, and
# second indices
a[[3, -1, 1]]

array([19, 99,  3])

In [56]:
# pull out the Fibonacci sequence
fib = np.array([0, 1, 1, 2, 3, 5])
a[fib]

array([ 1,  3,  3,  9, 19, 51])

In [57]:
# pull out a 2x2 array
a[[[[2, 7], [4, 2]]]] 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


array([[ 9, 99],
       [33,  9]])

In [58]:
a = np.arange(16) - 8
a.shape = (4, 4)
a

array([[-8, -7, -6, -5],
       [-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [59]:
# pull out the third, last, and
# first columns
a[:, [2, -1, 0]]

array([[-6, -5, -8],
       [-2, -1, -4],
       [ 2,  3,  0],
       [ 6,  7,  4]])

In [60]:
# pull out a Fibonacci sequence of
# rows for every other column, starting
# from the back
fib = np.array([0, 1, 1, 2, 3])
a[fib, ::-2]

array([[-5, -7],
       [-1, -3],
       [-1, -3],
       [ 3,  1],
       [ 7,  5]])

In [61]:
# get the diagonal with a range
i = np.arange(4)
a[i, i]

array([-8, -3,  2,  7])

In [62]:
# lower diagonal by subtracting one to 
# part of the range
a[i[1:], i[1:] - 1]

array([-4,  1,  6])

In [64]:
# upper diagonal by adding one to part 
# of the range
a[i[:3], i[:3] + 1]

array([-7, -2,  3])

In [65]:
# anti-diagonal by reversal
a[i, i[::-1]]

array([-5, -2,  1,  4])

In [66]:
# create an array
a = np.arange(9)
a.shape = (3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
# create an all True mask
m = np.ones(3, dtype=bool)
m

array([ True,  True,  True])

In [68]:
# take the diagonal
a[m, m]

array([0, 4, 8])

In [69]:
# create a mask
m = np.array([[1, 0, 1], 
              [False, True, False], 
              [0, 0, 1]], dtype=bool)

a[m]

array([0, 2, 4, 8])

In [70]:
a < 5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [71]:
m = (a >= 7)

In [72]:
a[m]

array([7, 8])

In [73]:
a[a < 5]

array([0, 1, 2, 3, 4])

In [74]:
np.array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [75]:
a[(a < 5) | (a >= 7)]

array([0, 1, 2, 3, 4, 7, 8])

In [76]:
np.array([0, 1, 2, 3, 4, 7, 8])

array([0, 1, 2, 3, 4, 7, 8])

In [77]:
np.where(a < 5)

(array([0, 0, 0, 1, 1]), array([0, 1, 2, 0, 1]))

In [78]:
a[np.where(a >= 7)]

array([7, 8])

In [79]:
a[:, np.where(a < 2)[1]]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [80]:
# a simple flat dtype
fluid = np.dtype([
    ('x', int),
    ('y', np.int64),
    ('rho', 'f8'),
    ('vel', 'f8'),
    ])

# a dtype with a nested dtype
# and a subarray
particles = np.dtype([
    ('pos', [('x', int), 
             ('y', int), 
             ('z', int)]),
    ('mass', float), 
    ('vel', 'f4', 3)
    ])

In [81]:
particles.names

('pos', 'mass', 'vel')

In [82]:
fluid.fields

mappingproxy({'rho': (dtype('float64'), 16),
              'vel': (dtype('float64'), 24),
              'x': (dtype('int64'), 0),
              'y': (dtype('int64'), 8)})

In [83]:
np.zeros(4, dtype=particles)

array([((0, 0, 0), 0., [0., 0., 0.]), ((0, 0, 0), 0., [0., 0., 0.]),
       ((0, 0, 0), 0., [0., 0., 0.]), ((0, 0, 0), 0., [0., 0., 0.])],
      dtype=[('pos', [('x', '<i8'), ('y', '<i8'), ('z', '<i8')]), ('mass', '<f8'), ('vel', '<f4', (3,))])

In [84]:
# note that the rows are tuples
f = np.array([(42, 43, 6.0, 2.1), 
              (65, 66, 128.0, 3.7), 
              (127, 128, 3.0, 1.5)],
             dtype=fluid)
f

array([( 42,  43,   6., 2.1), ( 65,  66, 128., 3.7),
       (127, 128,   3., 1.5)],
      dtype=[('x', '<i8'), ('y', '<i8'), ('rho', '<f8'), ('vel', '<f8')])

In [85]:
f[1]

(65, 66, 128., 3.7)

In [86]:
f[::2]

array([( 42,  43, 6., 2.1), (127, 128, 3., 1.5)],
      dtype=[('x', '<i8'), ('y', '<i8'), ('rho', '<f8'), ('vel', '<f8')])

In [94]:
f['rho']

array([  6., 128.,   3.])

In [87]:
f[['vel', 'x', 'rho']]

array([(2.1,  42,   6.), (3.7,  65, 128.), (1.5, 127,   3.)],
      dtype={'names':['vel','x','rho'], 'formats':['<f8','<i8','<f8'], 'offsets':[24,0,16], 'itemsize':32})

In [88]:
x = np.linspace(0.0, np.pi, 5)

In [89]:
np.sin(x)

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

In [90]:
a = np.arange(9)
a.shape = (3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
np.sum(a)

36

In [92]:
np.sum(a, axis=0)

array([ 9, 12, 15])

In [93]:
np.sum(a, axis=1)

array([ 3, 12, 21])